### ISSUE TITLE
custom permalink plugin gets disabled automatically after cache purge

### ISSUE THREAD

**Issue by fusionlabltd** [samiahmedsiddiqui/custom-permalinks#57]
Hi,  custom permalink plugin gets disabled automatically after purging opcache. The plugin seems to have an issue with wp-opcache or wp-rocket. If wp-opcache is enabled, we cannot activate the customer permalink plugin.

**Comment by samiahmedsiddiqui** [comment]
@fusionlabltd I have tested the plugin with [WP OPcache](https://wordpress.org/plugins/flush-opcache/) and it is working fine for me. Please give it a try again with Custom Permalinks `v2.4.0` that is released today. Maybe, this issue is already fixed in the `v2.4.0`. 

If the issue still persist then please let me know the following details.

1. WordPress Version
2. PHP Version
3. Hosting server
4. Cache plugin name and URL
5. Any scenario (That I can use to replicate the issue)

**Comment by samiahmedsiddiqui** [comment]
As per not getting any response from along time, I am closing this issue.
