### ISSUE TITLE
URLs with question mark (?) and equal sign (=) are not redirected correctly

### ISSUE THREAD

**Issue by Knocks** [samiahmedsiddiqui/custom-permalinks#79]
This plugin does not process URLs that contain the question mark and equal sign, for example:

/storyview.php?StoryID=20200311-12492

The plugin strips the question mark out and the resulting URL becomes

/storyview.phpStoryID20200311-12492

This results in 404 errors in cases where those question marks are contained in the original URLs.

**Comment by tomjn** [comment]
**This isn't the plugins fault**, WordPress itself is doing it because that would be an invalid slug, and these aren't redirects either.

Such a slug would be invalid and the resulting post would be impossible to visit due to the fundamentals of how URLs work. Everything after the `?` would be stripped out of the path by the browser and turned into URL parameters, resulting in requests with a path of `storyview.php` not `/storyview.php?StoryID=20200311-12492`.

You can't put URL parameters in a slug, for the same reason they can't go in the path part of a URL. _Or more specifically, `sanitize_title` prevents it._

**Comment by tomjn** [comment]
Note that nothing stops you rewriting the canonical URL of a post to `/storyview.php?StoryID=20200311-12492` or changing the URLs when they're rendered, or filtering the sitemap. The problem is not that you can't have that URL, it's that the approach taken to achieve it is incorrect. Lots of alternatives exist.

**Comment by Knocks** [comment]
Understood, thanks @tomjn

**Comment by samiahmedsiddiqui** [comment]
@tomjn Thank you for promptly addressing the matter and providing clarifications. Your response is much appreciated.

**Comment by tomjn** [comment]
I’d note that there may be a UX issue here if users can add and save
invalid permalinks though, it might be worth adding a regex to warn users
so they don’t save the result then see it’s been stripped/sanitised at a
later date

I expect sanitize title might have such a regex but it should be straight
forward with a URL regex

**Comment by Knocks** [comment]
I have researched this further, and an equal sign is not an invalid character in URLs, nor is it officially reserved syntax for queries.  Using key=value is just a convention.  So an equal sign can be safely included to the exceptions list (even though it's not useful in my particular case).

**Comment by tomjn** [comment]
That is true, = is valid in URL paths though that’s not to say it is a
valid WP slug especially given how rewrite rules work

Take the example of a page with the slug of =, it would result in
index.php?pagename== which wouldn’t work.

You could work around this with URL encoding but then it would no longer be
an = character and it wouldn’t be found in the database.


To emphasise, even if this plugin successfully saved and supported these
characters, it’s pointless if WordPress itself is unable to support it

**Comment by tomjn** [comment]
And even if it was possible, it wouldn’t work in the given examples because
of the ?.

A test case might be “myvalue=yes” as a post slug. It would be possible to
craft a rewrite rule with an = as long as it resolved to a URL that didn’t
contain the =.

In the case of a ? the URL would be broken into path and parameters by the
browser before a connection was even made so even if WP supported it,
there’s no way to actually make that request without the browser
reinterpretting it.


I know I said this on stack exchange but you can’t migrate abc.php?xyz=123
URLs to posts by putting URL parameters in their slugs and permalinks. That
doesn’t mean you can’t keep your existing URLs, it just means
permalinks/rewrite rules are not how you do it, no matter which plugin you
try to use. Not because I said so or the plugin author won’t do it, but
because it’s a fundamental part of how URLs work and how WordPress URL
handling and post storage works.

**Comment by Knocks** [comment]
Yes, I accept that the ? is the troublesome part, but the = part is not.  I think our point of contention is that you insist that something is or isn't a valid slug, whereas this and other permalink plugins don't make any claims about writing a perfect slug.  The advertised function of the plugin is that it will assign a permalink of your choosing to the post/page that you want.  Do you think an average person knows very much about query parameters?  

Sometimes you have to adopt the mindset of the end user (that's a critical part of UX), who sees an advertised product function, installs the product, tries to execute that function, and when it doesn't work, he comes to SE or Github to ask why it doesn't work.

In this case, there is no reason to exclude = as an invalid character, because the plugin works with this character, and the URLs resolve to correct posts.  You never know what funky URLs users are trying to preserve or revive.

**Comment by tomjn** [comment]
Note again that permalinks are _not_ redirects, and the example you reported as not working does not contain a URL path with a `=` in it. The editor also works this way and will strip the `=` out from post slugs. Rewrite rule analyser suggests it will only match the generic pages rewrite rule too so even if it was a post slug it wouldn't even trigger the rewrite rules responsible.

This means you'd need to write custom code to add a rewrite rule to support an `=`.

WordPress does not support posts with slugs that contain `=`. Modify the database directly to put a `=` in a slug and try it for yourself, it will not work, plugin or no plugin. The closest you might be able to get is with a page. _But you don't need it to work to achieve your goal._

> Sometimes you have to adopt the mindset of the end user (that's a critical part of UX), who sees an advertised product function, installs the product, tries to execute that function, and when it doesn't work, he comes to SE or Github to ask why it doesn't work.

Then perhaps you're not asking why `=` and `?` don't work, but are instead reporting that you were allowed to enter them when you should not? If so that's not what your issue said and you should have raised a new issue with that

Again, you can have the URLs you want ( `/storyview.php?StoryID=20200311-12492` ) just not by doing it this way. And it's not true that all other alternatives involve 301 redirects ( though that wouldn't be such a terrible thing or impact SEO anyway ).

Unfortunately you've not attempted to ask how to do this anywhere, and have instead focused on how to implement the solutions you've devised :(

**Comment by Knocks** [comment]
Tom, you are not even reading my posts before replying.  I have accepted that the original post is now moot, because inserting a question mark via a permalink plugin is most likely not going to work.  You made sure to hammer this point sufficiently, yet you continue to repeat it as if your readers lack the ability to understand you.

We are no longer discussing the original question.  This issue is closed.  We are merely discussing a side point that arose, which is that the equal sign is a perfectly acceptable part of a URL, regardless of whether it makes a valid slug, and there is no reason for it to be in the exceptions list for this particular plugin.  I changed 3 characters in this plugin's code, and the equal sign works in custom permalinks.  This plugin advertises custom permalinks, not custom slugs, and there is apparently a myth out there that the equal sign is one of those characters that might interfere with query parameters.  It doesn't.

As for my original question, I am, in fact, working on it, just not on SE, where the most common response is a condescending and patronizing "You are asking the wrong question" and ruthless downvoting.  It's a horrible user experience, and the WordPress official forums leave much to be desired as well.  I'd rather pay someone to do write a working solution than deal with the toxicity of SE and the lackluster support for most WordPress products.
